# Generated by Django 5.0.1 on 2024-01-19 00:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ae6ab67-4a48-4f4c-8367-92f286db93a0'), primary_key=True, serialize=False, unique=True),
        ),
    ]
