# Generated by Django 5.0.1 on 2024-01-20 21:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='email', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4bcc6561-7e96-4c30-977c-51bd3317e512'), primary_key=True, serialize=False, unique=True),
        ),
    ]
