# Generated by Django 5.0.1 on 2024-03-07 01:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_auth_provider_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('03042aec-ff84-4c89-a1f3-eedb6639ac8d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
