# Generated by Django 5.0.1 on 2024-03-07 01:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('38b1f0ae-333c-430c-bc59-678090c2d094'), primary_key=True, serialize=False, unique=True),
        ),
    ]
